In [ ]:
NICKNAME = "Vlad11000"

In [2]:
1
import numpy as np

In [2]:
2
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Boss/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Boss/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Boss/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Boss/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Boss/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Boss/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Boss/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Boss/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
    

In [3]:
3
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
4
x = np.zeros((15,7))
print("%d bytes" % (x.size * x.itemsize))

840 bytes


In [6]:
5
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [7]:
6
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
7
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [15]:
8
x = x[::-1]
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [16]:
9
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
10
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [18]:
11
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
12
x = np.random.random((3,3,3))
print(x)

[[[0.83693509 0.42608648 0.34116024]
  [0.77308011 0.03605632 0.71012927]
  [0.38284694 0.32087439 0.56193124]]

 [[0.08259433 0.82282138 0.72752747]
  [0.23355592 0.21333676 0.04607821]
  [0.46533038 0.47142827 0.8486769 ]]

 [[0.11443614 0.45337863 0.99876624]
  [0.39322415 0.21033595 0.81268043]
  [0.71298909 0.12601812 0.73264207]]]


In [20]:
13
x = np.random.random((10,10))
xmin, xmax = x.min(), x.max()
print(xmin, xmax)

0.021725689498123257 0.9996002021823613


In [21]:
14
x = np.random.random(30)
a = x.mean()
print(a)

0.5272071623902626


In [23]:
15
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
16
x = np.ones((5,5))
x = np.pad(x, 1, constant_values=0)
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [25]:
17
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [26]:
18
x = np.diag(np.arange(1, 5), k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [27]:
19
x = np.zeros((8,8), dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
20
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [29]:
21
x = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [30]:
22
x = np.random.random((5, 5))
norms = np.linalg.norm(x, axis=1)
x1 = x / norms
x1

array([[0.48525132, 0.45928625, 0.62370157, 0.18721696, 0.73693782],
       [0.01410299, 0.21239452, 0.44307362, 0.35680133, 0.7258303 ],
       [0.56372208, 0.19363116, 0.44562447, 0.30075537, 0.32402042],
       [0.43975264, 0.94033921, 0.09801457, 0.42612691, 0.89588364],
       [0.61344441, 0.28580307, 0.02916563, 0.12329837, 0.45608235]])

In [31]:
23
color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])

In [32]:
24
a = np.random.random((5, 3))
b = np.random.random((3, 2))
c = a @ b
c

array([[0.85691535, 1.21859354],
       [0.56213609, 0.99594461],
       [0.87748633, 1.17737322],
       [0.74861153, 1.31844199],
       [0.6630173 , 0.91537087]])

In [33]:
25
x = np.random.random(18)
for i in range(4, 8):
    x[i] *= -1
x

array([ 0.03286518,  0.29880678,  0.51250045,  0.77322469, -0.94293814,
       -0.39716179, -0.36880371, -0.09202617,  0.45277253,  0.80977398,
        0.35386112,  0.155222  ,  0.92671732,  0.70201143,  0.83074302,
        0.67631046,  0.29282824,  0.75327583])

In [34]:
26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [36]:
27
x = np.arange(4)
x**x
2 << x >> 2
x <- x
1j*x
x/1/1
x<x>x #не это

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [39]:
28
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\Boss\AppData\Local\Temp\ipykernel_5952\2538865916.py:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\Boss\AppData\Local\Temp\ipykernel_5952\2538865916.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

In [40]:
30
x = np.random.randint(0, 13, 7)
y = np.random.randint(0, 13, 7)
z = np.intersect1d(x, y)
z

array([10, 11])

In [41]:
31
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [42]:
err = np.seterr(all="ignore")
_ = np.seterr(**err)

In [43]:
32
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [44]:
33
y = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tod = np.datetime64('today', 'D')
tom = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(y, tod, tom)

2022-12-21 2022-12-22 2022-12-23


In [45]:
34
J = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(J)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [46]:
35
A = np.ones(4)*4
B = np.ones(4)
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-10., -10., -10., -10.])

In [47]:
36
x = np.random.uniform(0, 24, size=10)
print(x - x % 1)
print(x // 1)
print(np.floor(x))
print(np.trunc(x))

[ 7.  9. 11. 22. 22. 14.  1. 17. 11.  3.]
[ 7.  9. 11. 22. 22. 14.  1. 17. 11.  3.]
[ 7.  9. 11. 22. 22. 14.  1. 17. 11.  3.]
[ 7.  9. 11. 22. 22. 14.  1. 17. 11.  3.]


In [48]:
37
x = np.arange(5)
x0 = x
for i in range(4):
    x = np.vstack((x, x0)) 
x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [49]:
38
def gen():
    for x in range(10):
        yield x
x = np.fromiter(gen(),dtype=float,count=-1)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [50]:
39
x = np.random.uniform(0.1, 1, 10)
x

array([0.33860981, 0.86330872, 0.94539249, 0.21040754, 0.79679066,
       0.69716378, 0.34220082, 0.3105764 , 0.23212085, 0.31131255])

In [51]:
40
x = np.random.random(10)
x.sort()
x

array([0.03021866, 0.40514835, 0.44163703, 0.58100215, 0.62006902,
       0.68684012, 0.74307769, 0.91996908, 0.94716681, 0.98113069])

In [52]:
41
x = np.arange(10)
np.add.reduce(x)

45

In [53]:
42
a = np.random.random(10)
b = np.random.random(10)
np.allclose(a, b)

False

In [54]:
43
a = np.zeros(10)
a.flags.writeable = False

In [55]:
44
def cartesian_to_polar(c):
    p = np.array([[np.sqrt(x**2 + y**2), np.arctan2(y, x)] for x, y in c])
    return p
x = np.random.random((10,2))
cartesian_to_polar(x)

array([[1.20463247, 0.6203699 ],
       [0.81212435, 0.14608016],
       [0.94616661, 1.12993166],
       [0.63399623, 0.37419028],
       [0.9763065 , 0.37099677],
       [0.10450871, 0.25052191],
       [0.39061711, 1.1565126 ],
       [0.84194953, 0.94348109],
       [0.98753427, 0.99410702],
       [0.89270187, 1.39994519]])

In [56]:
45
x = np.random.random(10)
print(x)
x[x.argmax()] = 0
print(x)

[0.89417694 0.15273466 0.41020066 0.84132513 0.68850355 0.76744482
 0.25479387 0.89394192 0.89275782 0.7274683 ]
[0.         0.15273466 0.41020066 0.84132513 0.68850355 0.76744482
 0.25479387 0.89394192 0.89275782 0.7274683 ]


In [58]:
46
a= np.zeros((5, 5), [('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [59]:
47
x = np.random.uniform(0.1, 10, 4)
y = np.random.uniform(0.1, 10, 4)
c = 1.0 / (x.reshape((-1, 1)) - y)
c

array([[-0.97516776,  0.214167  ,  0.38827309,  1.76789708],
       [-0.28575129,  0.45554531,  9.85952935, -0.52398863],
       [ 1.42591109,  0.15634713,  0.23243503,  0.43622131],
       [-0.40410601,  0.31054745,  0.88780516, -1.13187497]])

In [60]:
48
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


In [61]:
49
np.set_printoptions(threshold = float("inf"))
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [62]:
50
x = np.arange(241)
v = np.random.uniform(0,100)
i = (np.abs(x-v)).argmin()
print(x[i])

89


In [63]:
51
a = np.zeros(10, [ ('position', [ ('x', float, 1), ('y', float, 1)]),
                   ('color',    [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Boss\AppData\Local\Temp\ipykernel_5952\716841596.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [ ('position', [ ('x', float, 1), ('y', float, 1)]),


In [64]:
52
import scipy.spatial as sp
x = np.random.random((10, 2))
D = sp.distance.cdist(x, x)
print(D)

[[0.         0.501552   0.15753817 0.52138898 0.60924167 0.45884355
  0.62261419 0.8310793  0.76449771 0.50984175]
 [0.501552   0.         0.34787818 0.09403977 0.5524863  0.66624863
  0.26071956 0.50291777 0.30792906 0.50631199]
 [0.15753817 0.34787818 0.         0.37836935 0.57271421 0.50615719
  0.50060618 0.72775904 0.60752166 0.42481888]
 [0.52138898 0.09403977 0.37836935 0.         0.47023674 0.61495603
  0.16815049 0.4126418  0.36724814 0.59441505]
 [0.60924167 0.5524863  0.57271421 0.47023674 0.         0.30475047
  0.36914651 0.37447592 0.8319594  0.96444476]
 [0.45884355 0.66624863 0.50615719 0.61495603 0.30475047 0.
  0.58880955 0.6690991  0.97368778 0.93081662]
 [0.62261419 0.26071956 0.50060618 0.16815049 0.36914651 0.58880955
  0.         0.24572091 0.47887952 0.76180894]
 [0.8310793  0.50291777 0.72775904 0.4126418  0.37447592 0.6690991
  0.24572091 0.         0.66559702 1.00703218]
 [0.76449771 0.30792906 0.60752166 0.36724814 0.8319594  0.97368778
  0.47887952 0.665597

In [65]:
53
x = np.arange(10, dtype=np.float32)
x = x.astype(np.int32, copy=False)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [67]:
55
x = np.arange(9).reshape(3,3)
for i, value in np.ndenumerate(x):
    print(i, value)
for i in np.ndindex(x.shape):
    print(i, x[i])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [68]:
56
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X**2 + Y**2)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D - mu)**2 / (2 * sigma**2) ))
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [69]:
57
p = 3
A = np.zeros((5,5))
np.put(A, np.random.choice(range(5*5), p, replace=False),1)
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]


In [70]:
58
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
y = x - x.mean(axis=1).reshape(-1, 1)
print(y)

[[-0.24045371  0.13067431  0.42294177  0.37620735 -0.02336168 -0.42167691
   0.27218172 -0.37364956 -0.05584782 -0.08701548]
 [ 0.12732535 -0.11616597  0.34299381 -0.23724294 -0.36032184  0.41452185
   0.41259562  0.25262277 -0.37318668 -0.46314197]
 [ 0.03525367  0.19941048 -0.16211738  0.27782741  0.34991095 -0.23842605
  -0.13614113  0.38508473 -0.4107436  -0.30005908]
 [ 0.15534663  0.15891403  0.1823042  -0.48439061  0.32952065 -0.26055124
   0.19516936 -0.44433686  0.03856535  0.12945848]
 [-0.16409613  0.01255065  0.09457106  0.32353659  0.06426762 -0.34357512
   0.21632513  0.11793725 -0.07292395 -0.24859312]]


In [71]:
59
n = 2
a = np.random.randint(0, 10, (3, 4))
print(a)
print(a [a[:, n].argsort() ])

[[3 1 5 3]
 [1 2 9 9]
 [5 9 0 1]]
[[5 9 0 1]
 [3 1 5 3]
 [1 2 9 9]]


In [72]:
60
a = np.random.randint(0, 2, (3, 4))
print((~a.any(axis = 0)).any())

True


In [73]:
61
x = np.random.uniform(0, 10, 10)
a = 6
m = x.flat[np.abs(x - a).argmin()]
print(m)

6.334853174726213


In [74]:
62
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [76]:
64
x = np.ones(10)
y = np.random.randint(0, 10, 20)
np.add.at(x, y, 1)
print(x)

[3. 3. 2. 3. 3. 4. 3. 5. 3. 1.]


In [3]:
64
x = np.ones(10)
y = np.random.randint(0, 10, 20)
np.add.at(x, y, 1)
print(x)

[4. 6. 4. 2. 4. 2. 2. 2. 2. 2.]


In [4]:
65
X = np.arange(6)
I = np.random.randint(0, 10, 6)
F = np.bincount(I, X)
print(F)

[0. 0. 0. 0. 0. 7. 0. 4. 1. 3.]


In [5]:
66
w, h = 16, 16
I = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)
F = I[..., 0] * 256 * 256 + I[..., 1] * 256 + I[..., 2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [6]:
67
A = np.random.randint(0, 10, (3, 4, 3, 4))
sum = A.sum(axis=(-2, -1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[53 40 51 59]
 [44 51 55 55]
 [48 54 47 58]]
[[53 40 51 59]
 [44 51 55 55]
 [48 54 47 58]]


In [7]:
68
import pandas as pd
D = np.random.uniform(0, 1, 33)
S = np.random.randint(0, 10, 33)
print(pd.Series(D).groupby(S).mean())

0    0.513107
1    0.527412
2    0.389092
3    0.293930
4    0.766198
5    0.568771
6    0.405479
7    0.537744
8    0.308401
9    0.308079
dtype: float64


In [8]:
69
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))
print(np.diag(np.dot(A, B)))

[0.96673969 0.76531091 1.62886059 1.8083264  0.65207941]


In [9]:
70
a = np.linspace(1, 5, 5)
b = np.zeros(5 + 4 * 3)
b[::4] = a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [10]:
71
A = 7 * np.ones((5, 5, 3))
B = 3 * np.ones((5, 5))
print(A * B[:,:,None])

[[[21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]]

 [[21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]]

 [[21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]]

 [[21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]]

 [[21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]
  [21. 21. 21.]]]


In [11]:
72
A = np.arange(25).reshape(5,5)
A[[0, 1]] = A[[1, 0]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
73
p = np.random.randint(0, 100, (10, 3))
F = np.roll(p.repeat(2, axis=1), -1, axis=1)
F = F.reshape(len(F) * 3, 2)
F = np.sort(F, axis=1)
G = F.view( dtype=[('0', F.dtype), ('1', F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 48) ( 0, 89) ( 2, 55) ( 2, 64) ( 5, 56) ( 5, 57) (16, 35) (16, 91)
 (25, 70) (25, 74) (34, 41) (34, 79) (35, 91) (41, 79) (48, 51) (48, 73)
 (48, 89) (51, 73) (55, 64) (55, 66) (55, 73) (56, 57) (66, 73) (69, 73)
 (69, 89) (70, 74) (71, 75) (71, 83) (73, 89) (75, 83)]


In [13]:
74
x = np.sort([0, 1, 1, 3, 2, 1, 7])
k = np.bincount(x)
A = np.repeat(np.arange(len(k)), k)
print(A)

[0 1 1 1 2 3 7]


In [14]:
75
from numpy.lib.stride_tricks import sliding_window_view
x = np.arange(14)
print(sliding_window_view(x, window_shape=6).mean(axis=-1))

[ 2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5]


In [15]:
76
Z = np.arange(9)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]


In [16]:
77
x = np.random.randint(0, 3, 34)
print (x)
print(np.logical_not(x, out=x))
x = np.random.uniform(-1.0, 1.0, 33)
print (x)
print(np.negative(x, out=x))

[2 2 0 1 1 0 1 2 0 1 0 0 2 1 2 1 1 2 2 2 1 0 0 0 0 1 1 1 2 0 1 2 2 1]
[0 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 0 0 0]
[-0.52207434  0.40054455  0.77174765 -0.79304046  0.42009828  0.58078331
  0.63229644  0.43903848 -0.56928089  0.09276177 -0.23952682 -0.50342632
 -0.62807215 -0.55968684 -0.57296633 -0.56928625 -0.28485412 -0.65347818
 -0.32400095  0.70652139  0.97830362 -0.55841739  0.48994179 -0.18185496
 -0.22345228  0.53885781 -0.51701679  0.08017635 -0.2603506  -0.54505931
 -0.39424698 -0.2013105   0.84571267]
[ 0.52207434 -0.40054455 -0.77174765  0.79304046 -0.42009828 -0.58078331
 -0.63229644 -0.43903848  0.56928089 -0.09276177  0.23952682  0.50342632
  0.62807215  0.55968684  0.57296633  0.56928625  0.28485412  0.65347818
  0.32400095 -0.70652139 -0.97830362  0.55841739 -0.48994179  0.18185496
  0.22345228 -0.53885781  0.51701679 -0.08017635  0.2603506   0.54505931
  0.39424698  0.2013105  -0.84571267]


In [17]:
81
x = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(x, window_shape=4))


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [18]:
83
x = np.arange(25).reshape(5,5)
rank = np.linalg.matrix_rank(x)
print(rank)

2


In [19]:
84
x = np.arange(100).reshape(10, 10)
print(sliding_window_view(x, window_shape=(3, 3)))

[[[[ 0  1  2]
   [10 11 12]
   [20 21 22]]

  [[ 1  2  3]
   [11 12 13]
   [21 22 23]]

  [[ 2  3  4]
   [12 13 14]
   [22 23 24]]

  [[ 3  4  5]
   [13 14 15]
   [23 24 25]]

  [[ 4  5  6]
   [14 15 16]
   [24 25 26]]

  [[ 5  6  7]
   [15 16 17]
   [25 26 27]]

  [[ 6  7  8]
   [16 17 18]
   [26 27 28]]

  [[ 7  8  9]
   [17 18 19]
   [27 28 29]]]


 [[[10 11 12]
   [20 21 22]
   [30 31 32]]

  [[11 12 13]
   [21 22 23]
   [31 32 33]]

  [[12 13 14]
   [22 23 24]
   [32 33 34]]

  [[13 14 15]
   [23 24 25]
   [33 34 35]]

  [[14 15 16]
   [24 25 26]
   [34 35 36]]

  [[15 16 17]
   [25 26 27]
   [35 36 37]]

  [[16 17 18]
   [26 27 28]
   [36 37 38]]

  [[17 18 19]
   [27 28 29]
   [37 38 39]]]


 [[[20 21 22]
   [30 31 32]
   [40 41 42]]

  [[21 22 23]
   [31 32 33]
   [41 42 43]]

  [[22 23 24]
   [32 33 34]
   [42 43 44]]

  [[23 24 25]
   [33 34 35]
   [43 44 45]]

  [[24 25 26]
   [34 35 36]
   [44 45 46]]

  [[25 26 27]
   [35 36 37]
   [45 46 47]]

  [[26 27 28]
   [36 37 38]


In [20]:
86
p, n = 7, 14
A = np.ones((p, n, n))
B = np.ones((p, n, 1))
C = np.tensordot(A, B, axes=[[0, 2], [0, 1]])
print(C)


[[98.]
 [98.]
 [98.]
 [98.]
 [98.]
 [98.]
 [98.]
 [98.]
 [98.]
 [98.]
 [98.]
 [98.]
 [98.]
 [98.]]


In [21]:
87
x = np.arange(16**2).reshape(16,16)
k = 4
print(sliding_window_view(x, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[ 408  472  536  600]
 [1432 1496 1560 1624]
 [2456 2520 2584 2648]
 [3480 3544 3608 3672]]


In [22]:
89
x = np.random.randint(0, 44, 34)
np.random.shuffle(x)
n = 7
print(x)
print(x[np.argsort(x)[-n:]])



[13 37 27 23 11 10 40 25 18 16 25 32 10  1 28 15 10 24  8  9 24 19 22 31
 35 19  2 23 35 34 24 40 33 29]
[33 34 35 35 37 40 40]


In [23]:
91
b = [(1, 1), (2, 4), (3, 9)]
c = np.core.records.array(b, formats = ['i2', 'f2'], names = ('x', 'y'))
c

rec.array([(1, 1.), (2, 4.), (3, 9.)],
          dtype=[('x', '<i2'), ('y', '<f2')])

In [24]:
90
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [25]:
95
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [26]:
96
X = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(X).view(np.dtype((np.void, X.dtype.itemsize * X.shape[1])))
k, i = np.unique(T, return_index=True)
u = X[i]
print(u)

[[1 0 1]
 [1 1 0]
 [1 1 1]]


In [27]:
97
A = np.random.randint(0, 2, (3, 4))
n = 2
M = np.logical_and.reduce(np.mod(A, 1) == 0, axis=-1)
M &= (A.sum(axis=-1) == n)
print(A)
print(A[M])

[[1 0 0 0]
 [0 1 1 0]
 [1 1 0 0]]
[[0 1 1 0]
 [1 1 0 0]]
